export const GET_PARTICIPANTS = 'GET_PARTICIPANTS';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_HIGHSCORE = 'GET_HIGHSCORE';
export const GET_CAUGHT_AGENTS = 'GET_CAUGHT_AGENTS';
export const INVALID_AGENT_CODE = 'INVALID_AGENT_CODE';