export const GET_PARTICIPANTS = 'GET_PARTICIPANTS';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_HIGHSCORE = 'GET_HIGHSCORE';
export const GET_CAUGHT_AGENTS = 'GET_CAUGHT_AGENTS';
export const AGENT_CODE_MESSAGE = 'INVALID_AGENT_CODE';
export const FETHCING_PARTICIPANTS = 'FETHCING_PARTICIPANTS';
export const CLICK_TAG = 'CLICK_TAG';